#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
CREATE ROLE ${DB_OWNER_USER} LOGIN PASSWORD '${DB_OWNER_PASSWORD}' NOSUPERUSER NOCREATEROLE NOBYPASSRLS;
CREATE ROLE ${DB_APP_USER} LOGIN PASSWORD '${DB_APP_PASSWORD}' NOSUPERUSER NOCREATEROLE NOCREATEDB NOBYPASSRLS;
CREATE ROLE ${DB_WORKER_USER} LOGIN PASSWORD '${DB_WORKER_PASSWORD}' NOSUPERUSER NOCREATEROLE NOCREATEDB NOBYPASSRLS;
CREATE DATABASE ${DB_NAME} OWNER ${DB_OWNER_USER};
CREATE DATABASE ${DB_TEST_NAME} OWNER ${DB_OWNER_USER};
SQL

for db in "${DB_NAME}" "${DB_TEST_NAME}"; do
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$db" <<SQL
REVOKE ALL ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO ${DB_OWNER_USER};
GRANT USAGE ON SCHEMA public TO ${DB_APP_USER}, ${DB_WORKER_USER};
REVOKE ALL ON DATABASE ${db} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${db} TO ${DB_APP_USER}, ${DB_WORKER_USER};
SQL
done
